// Geometric Tools Library
// https://www.geometrictools.com
// Copyright (c) 2025 Geometric Tools LLC
// Distributed under the Boost Software License, Version 1.0
// https://www.boost.org/LICENSE_1_0.txt
// Version: 0.0.2025.01.12

#pragma once

// Top-level control over which tests are executed. The commented out tests
// with "//*" are failing and need investigating. Those commented out with
// "//?" need unit testing.

#define UT_UTILITY
#define UT_MATHEMATICS
#define UT_MATHEMATICS_ALGEBRA
#define UT_MATHEMATICS_ARITHMETIC
#define UT_MATHEMATICS_FUNCTIONS
#define UT_MATHEMATICS_MATRIXANALYSIS

// Mathematics
#if defined(UT_MATHEMATICS)

// Mathematics/Algebra
#if defined(UT_MATHEMATICS_ALGEBRA)
#define UT_MATHEMATICS_AFFINETRANSFORM
#define UT_MATHEMATICS_AXISANGLE
#define UT_MATHEMATICS_CONVERTCOORDINATES
#define UT_MATHEMATICS_DUALQUATERNION
#define UT_MATHEMATICS_EULERANGLES
#define UT_MATHEMATICS_LIEGROUPSALGEBRAS
#define UT_MATHEMATICS_MATRIX
#define UT_MATHEMATICS_MATRIXACCESSOR
#define UT_MATHEMATICS_POLYNOMIAL
#define UT_MATHEMATICS_QUATERNION
#define UT_MATHEMATICS_RIGIDMOTION
#define UT_MATHEMATICS_VECTOR
#endif

// Mathematices/Arithmetic
#if defined(UT_MATHEMATICS_ARITHMETIC)
#define UT_MATHEMATICS_APCONVERSION
#define UT_MATHEMATICS_APINTERVAL
#define UT_MATHEMATICS_BITHACKS
#define UT_MATHEMATICS_BSNUMBER
#define UT_MATHEMATICS_BSPRECISION
#define UT_MATHEMATICS_BSRATIONAL
#define UT_MATHEMATICS_CONSTANTS
#define UT_MATHEMATICS_IEEEBINARY
#define UT_MATHEMATICS_IEEEBINARY16
#define UT_MATHEMATICS_IEEEFUNCTIONS
#define UT_MATHEMATICS_QFNUMBER
#define UT_MATHEMATICS_SWINTERVAL
#define UT_MATHEMATICS_UINTEGERALU32
#define UT_MATHEMATICS_UINTEGERAP32
#define UT_MATHEMATICS_UINTEGERFP32
#endif

// Mathematics/Functions
#if defined(UT_MATHEMATICS_FUNCTIONS)
#define UT_MATHEMATICS_ACOSESTIMATE
#define UT_MATHEMATICS_ASINESTIMATE
#define UT_MATHEMATICS_ATANESTIMATE
#define UT_MATHEMATICS_CHEBYSHEVRATIO
#define UT_MATHEMATICS_CHEBYSHEVRATIOESTIMATE
#define UT_MATHEMATICS_COSESTIMATE
#define UT_MATHEMATICS_EXP2ESTIMATE
#define UT_MATHEMATICS_EXPESTIMATE
#define UT_MATHEMATICS_LOG2ESTIMATE
#define UT_MATHEMATICS_INVSQRTESTIMATE
#define UT_MATHEMATICS_LOGESTIMATE
#define UT_MATHEMATICS_REMEZALGORITHM
#define UT_MATHEMATICS_ROTATIONESTIMATE
#define UT_MATHEMATICS_SINESTIMATE
#define UT_MATHEMATICS_SLERP
#define UT_MATHEMATICS_SLERPESTIMATE
#define UT_MATHEMATICS_SQRTESTIMATE
#define UT_MATHEMATICS_TANESTIMATE
#endif

// Mathematics/MatrixAnalysis
#if defined(UT_MATHEMATICS_MATRIXANALYSIS)
#define UT_MATHEMATICS_BANDEDMATRIX
#define UT_MATHEMATICS_BLOCKCHOLESKYDECOMPOSITION
#define UT_MATHEMATICS_BLOCKLDLTDECOMPOSITION
#define UT_MATHEMATICS_CHOLESKYDECOMPOSITION
#define UT_MATHEMATICS_GAUSSIANELIMINATION
#define UT_MATHEMATICS_LDLTDECOMPOSITION
#define UT_MATHEMATICS_LINEARSYSTEM
#define UT_MATHEMATICS_SINGULARVALUEDECOMPOSITION
#define UT_MATHEMATICS_SYMMETRICEIGENSOLVER
#endif

#endif

// Utility
#if defined(UT_UTILITY)
#define UT_UTILITY_ATOMICMINMAX
#define UT_UTILITY_CONTAINERADAPTER
#define UT_UTILITY_HASHCOMBINE
#define UT_UTILITY_LATTICE
#define UT_UTILITY_MINHEAP
#define UT_UTILITY_MINIMUMSPANNINGTREE
#define UT_UTILITY_MULTIARRAY
#define UT_UTILITY_MULTIARRAYADAPTER
#define UT_UTILITY_RANGEITERATION
#define UT_UTILITY_RAWPTRCOMPARE
#define UT_UTILITY_SHAREDPTRCOMPARE
#define UT_UTILITY_STRINGUTILITY
#define UT_UTILITY_WEAKPTRCOMPARE
#endif
